version: '3.8'
services:
  database:
    container_name: postgres-dev
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    expose: [3000]
    environment:  # or use env_file as you did above
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database     # This is the name of the database service in this file above
      POSTGRES_PORT: 5432
    depends_on:
      - database

volumes:
  postgres-data:
